services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio
    restart: unless-stopped
    expose: ["4873"]
    ports: ["4873:4873"]
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_conf:/verdaccio/conf
      - verdaccio_plugins:/verdaccio/plugins
    networks: [web]

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]

networks:
  web:

volumes:
  verdaccio_storage:
  verdaccio_conf:
  verdaccio_plugins:
  caddy_data:
  caddy_config:

