import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { primitives } from '../src/primitives.js'
import { semantic, type SemanticTokens } from '../src/semantic.js'

function camelToKebab(str: string): string {
  return str.replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase()
}

function emitColorVars(tokens: SemanticTokens): string {
  return Object.entries(tokens)
    .map(([name, hex]) => `  --${camelToKebab(name)}: ${hex};`)
    .join('\n')
}

function emitRadiusVars(): string {
  return Object.entries(primitives.radius)
    .map(([name, value]) => `  --radius-${name}: ${value};`)
    .join('\n')
}

function emitFontVars(): string {
  return Object.entries(primitives.font)
    .map(([name, value]) => `  --font-${name}: ${value};`)
    .join('\n')
}

const css = `/* Auto-generated by packages/tokens/scripts/build-css.ts. Do not edit. */

:root {
${emitColorVars(semantic.light)}
${emitRadiusVars()}
${emitFontVars()}
}

.dark {
${emitColorVars(semantic.dark)}
}
`

const distDir = resolve(import.meta.dirname, '..', 'dist')
mkdirSync(distDir, { recursive: true })
writeFileSync(resolve(distDir, 'styles.css'), css, 'utf8')
console.log(`✓ wrote ${resolve(distDir, 'styles.css')}`)
